[supabase]
url = "https://fuwiytosszxecsrbfjwn.supabase.co" # Your Supabase Project URL
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1d2l5dG9zc3p4ZWNzcmJmanduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMDU5NDQsImV4cCI6MjA3ODY4MTk0NH0.2tCCpVlk_xTNM2M35YbkWLbIVr1JtoTVJx8IVru-k5Q" # Your Anon Public Key

[admin]
# This is a flag used in the app to check if the current user is YOU (the superuser)
# Replace "YourSuperuserName" with the exact name you will use to log in.
superuser_name = "Sneha0112"
